{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww18980\viewh14940\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 >>> from users_app.models import*\
>>> User.objects.create(first_name='Michelle',last_name='Han',email_address='michellehan@me.com',age=99)\
<User: User object (1)>\
>>> User.objects.create(first_name='Kylo',last_name='Ren',email_address='bensolo@me.com',age=99)\
<User: User object (2)>\
>>> User.objects.create(first_name='Tame',last_name='Impala',email_address='tameimpala@me.com',age=45)\
<User: User object (3)>\
>>> User.objects.get(id=1)\
<User: User object (1)>\
>>> User.objects.all()\
<QuerySet [<User: User object (1)>, <User: User object (2)>, <User: User object (3)>]>\
>>> User.objects.get(id=3)\
<User: User object (3)>\
>>> last_name='Pancakes'\
>>> save()\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
NameError: name 'save' is not defined\
>>> user.objects.get(id=3)\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
NameError: name 'user' is not defined\
>>> User.objects.get(id=3)\
<User: User object (3)>\
>>> user3=User.objects.get(id=3)\
>>> user3.last_name=\
  File "<console>", line 1\
    user3.last_name=\
                   ^\
SyntaxError: invalid syntax\
>>> user3.last_name='Pancakes'\
>>> user3.last_name = 'Pancakes'\
>>> user3.save()\
>>> User.objects.get(id=3)__dict__\
  File "<console>", line 1\
    User.objects.get(id=3)__dict__\
                                 ^\
SyntaxError: invalid syntax\
>>> User.objects.get(id=3).__dict__\
\{'_state': <django.db.models.base.ModelState object at 0x10319f850>, 'id': 3, 'first_name': 'Tame', 'last_name': 'Pancakes', 'email_address': 'tameimpala@me.com', 'age': 45, 'created_at': datetime.datetime(2020, 3, 11, 20, 53, 48, 925628, tzinfo=<UTC>), 'updated_at': datetime.datetime(2020, 3, 11, 21, 2, 48, 490061, tzinfo=<UTC>)\}\
>>> c=User.objects.get(id=2)\
>>> c.delete()\
(1, \{'users_app.User': 1\})\
>>> User.objects.all()order_by('first_name')\
  File "<console>", line 1\
    User.objects.all()order_by('first_name')\
                             ^\
SyntaxError: invalid syntax\
>>> User.objects.all().order_by('first_name')\
<QuerySet [<User: User object (1)>, <User: User object (3)>]>\
>>> User.objects.all().order_by(-'first_name').values()\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
TypeError: bad operand type for unary -: 'str'\
>>> User.objects.all().order_by('-first_name').values()\
<QuerySet [\{'id': 3, 'first_name': 'Tame', 'last_name': 'Pancakes', 'email_address': 'tameimpala@me.com', 'age': 45, 'created_at': datetime.datetime(2020, 3, 11, 20, 53, 48, 925628, tzinfo=<UTC>), 'updated_at': datetime.datetime(2020, 3, 11, 21, 2, 48, 490061, tzinfo=<UTC>)\}, \{'id': 1, 'first_name': 'Michelle', 'last_name': 'Han', 'email_address': 'michellehan@me.com', 'age': 99, 'created_at': datetime.datetime(2020, 3, 11, 20, 50, 15, 691036, tzinfo=<UTC>), 'updated_at': datetime.datetime(2020, 3, 11, 20, 50, 15, 691347, tzinfo=<UTC>)\}]>\
>>> }